pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const CHECKS=[['1.1','Samtal med nyttjaren.'],['1.2','Okulärbesiktning av dörrautomatik/dörrmiljö.'],['1.3','Kontroll av eventuella ombyggnader.'],['1.4','Kontroll fastsättning, infästning och efterdragning av skruvar.'],['1.5','Funktionskontroll manuell och automatisk öppning (kraft, dämpning & hastighet).'],['1.6','Funktionskontroll manuell och automatisk stängning (kraft, dämpning & hastighet).'],['1.7','Funktionskontroll öppnings- & stängningstider.'],['1.8','Funktionskontroll nödöppning & utrymning.'],['1.9','Kontroll/justering koordinator och armsystem.'],['1.10','Funktionskontroll impulsgivare (radar, armbågskontakter etc).'],['1.11','Sensorlister och säkerhetsanordningar.'],['1.12','Funktionskontroll låsfunktioner (dörrblad, elslutbleck, motorlås, ellås, låshus).'],['1.13','Kontroll/justering uppställningsmagnet & dörrstopp.'],['1.14','Kontroll gummiupphängningar, fjädrar, tryckslangar & tätning.'],['1.15','Kontroll motor, pump, hydraulik och drivaxel.'],['1.16','Kontroll säkringar / programväljare / styrmodul.'],['1.17','Behovsrengöring dörrautomatik och sensorlister.'],['1.18','Mindre justering.']];
let pdf,page=1,addMode=false,selected=null,doors=[],baseScale=1,zoom=1,pinch=null,dragging=null;
const $=x=>document.getElementById(x),canvas=$('pdfCanvas'),ctx=canvas.getContext('2d'),markers=$('markers'),wrap=$('viewerWrap');
try{doors=JSON.parse(localStorage.getItem('doors')||'[]')}catch(e){}
function normalize(d){d.checks=d.checks||{};CHECKS.forEach(([n])=>d.checks[n]=d.checks[n]||{result:'',note:''});['machineId','location','ao','nextDate','signature'].forEach(k=>d[k]=d[k]||'');return d}doors.forEach(normalize);
function save(){localStorage.setItem('doors',JSON.stringify(doors));$('doorCount').textContent=doors.length+' dörrar'}save();
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;pdf=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;page=1;zoom=1;await render(true)};
async function render(fit=false,focus=null){if(!pdf)return;const p=await pdf.getPage(page),natural=p.getViewport({scale:1});if(fit)baseScale=Math.min(1.6,(wrap.clientWidth-24)/natural.width);const oldW=canvas.width||1,oldH=canvas.height||1,oldSL=wrap.scrollLeft,oldST=wrap.scrollTop;const v=p.getViewport({scale:baseScale*zoom});canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);$('stage').style.width=canvas.width+'px';$('stage').style.height=canvas.height+'px';await p.render({canvasContext:ctx,viewport:v}).promise;$('pageInfo').textContent='Sida '+page+' / '+pdf.numPages;$('zoomInfo').textContent=Math.round(zoom*100)+'%';draw();if(focus){const rx=(oldSL+focus.x)/oldW,ry=(oldST+focus.y)/oldH;wrap.scrollLeft=rx*canvas.width-focus.x;wrap.scrollTop=ry*canvas.height-focus.y}}
function setZoom(z,focus={x:wrap.clientWidth/2,y:wrap.clientHeight/2}){zoom=Math.max(.5,Math.min(5,z));render(false,focus)}
$('zoomIn').onclick=()=>setZoom(zoom*1.25);$('zoomOut').onclick=()=>setZoom(zoom/1.25);$('fitBtn').onclick=()=>{zoom=1;render(true)};
$('prev').onclick=()=>{if(pdf&&page>1){page--;zoom=1;render(true)}};$('next').onclick=()=>{if(pdf&&page<pdf.numPages){page++;zoom=1;render(true)}};
$('addBtn').onclick=()=>{if(!pdf)return alert('Ladda upp en PDF först');addMode=!addMode;$('hint').style.display=addMode?'block':'none'};
markers.addEventListener('click',e=>{if(e.target!==markers||!addMode)return;const r=markers.getBoundingClientRect(),ids=new Set(doors.map(d=>d.id));let n=1;while(ids.has('D'+n))n++;const d=normalize({uid:Date.now()+''+Math.random(),id:'D'+n,page,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,model:'',status:'untested',notes:''});doors.push(d);selected=d.uid;addMode=false;$('hint').style.display='none';save();draw();show()});
function draw(){markers.innerHTML='';doors.filter(d=>d.page===page).forEach(d=>{const el=document.createElement('div');el.className='marker '+(d.status||'untested');el.textContent=d.id;el.style.left=d.x*100+'%';el.style.top=d.y*100+'%';el.addEventListener('pointerdown',ev=>{ev.stopPropagation();dragging=d.uid;el.setPointerCapture(ev.pointerId)});el.addEventListener('pointermove',ev=>{if(dragging!==d.uid)return;const r=markers.getBoundingClientRect();d.x=Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width));d.y=Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height));el.style.left=d.x*100+'%';el.style.top=d.y*100+'%'});el.addEventListener('pointerup',()=>{if(dragging===d.uid){dragging=null;selected=d.uid;save();show()}});el.onclick=ev=>{ev.stopPropagation();selected=d.uid;show()};markers.appendChild(el)})}
function cur(){return doors.find(d=>d.uid===selected)}
function buildChecklist(d){const box=$('checklist');box.innerHTML='';CHECKS.forEach(([n,t])=>{const r=document.createElement('div');r.className='checkrow';r.innerHTML='<div class="checktitle">'+n+' '+t+'</div><div class="checkcontrols"><select><option value="">Ej kontrollerad</option><option value="na">Ingår ej</option><option value="ok">Klart utan anm.</option><option value="remark">Klart med anm.</option></select><input placeholder="Anmärkning"></div>';const s=r.querySelector('select'),i=r.querySelector('input');s.value=d.checks[n].result;i.value=d.checks[n].note;s.onchange=()=>{d.checks[n].result=s.value;save()};i.oninput=()=>{d.checks[n].note=i.value;save()};box.appendChild(r)})}
function show(){const d=cur();$('empty').hidden=!!d;$('form').hidden=!d;if(!d)return;normalize(d);$('formTitle').textContent=d.id+' – Sida '+d.page;['doorId','model','status','notes','machineId','location','ao','nextDate','signature'].forEach(id=>$(id).value=d[id==='doorId'?'id':id]||'');buildChecklist(d)}
['doorId','model','status','notes','machineId','location','ao','nextDate','signature'].forEach(id=>$(id).oninput=()=>{const d=cur();if(!d)return;d[id==='doorId'?'id':id]=$(id).value;save();if(id==='doorId'||id==='status')draw()});
$('deleteBtn').onclick=()=>{const d=cur();if(d&&confirm('Ta bort '+d.id+'?')){doors=doors.filter(x=>x.uid!==d.uid);selected=null;save();draw();show()}};
wrap.addEventListener('touchstart',e=>{if(e.touches.length===2){const a=e.touches[0],b=e.touches[1],r=wrap.getBoundingClientRect();pinch={dist:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),zoom,focus:{x:(a.clientX+b.clientX)/2-r.left,y:(a.clientY+b.clientY)/2-r.top}}}}, {passive:true});
wrap.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){e.preventDefault();const a=e.touches[0],b=e.touches[1];$('zoomInfo').textContent=Math.round(Math.max(.5,Math.min(5,pinch.zoom*Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)/pinch.dist))*100)+'%'}},{passive:false});
wrap.addEventListener('touchend',e=>{if(pinch&&e.touches.length<2){const p=pinch;pinch=null;const shown=parseInt($('zoomInfo').textContent)/100;zoom=Math.max(.5,Math.min(5,shown));render(false,p.focus)}},{passive:true});
$('exportBtn').onclick=()=>{if(!doors.length)return alert('Det finns inga dörrar att spara.');const {jsPDF}=window.jspdf,doc=new jsPDF(),res={na:'Ingår ej',ok:'Klart utan anm.',remark:'Klart med anm.','':'Ej kontrollerad'},stat={untested:'Ej provad',ok:'Godkänd',fail:'Ej godkänd',action:'Åtgärd krävs'};doors.forEach((d,ix)=>{normalize(d);if(ix)doc.addPage();doc.setFontSize(16);doc.text('PROVNINGSPROTOKOLL DÖRRAUTOMATIK',14,16);doc.setFontSize(10);doc.text('Dörr: '+d.id+'   Maskin-ID: '+(d.machineId||'-'),14,25);doc.text('Placering: '+(d.location||'-')+'   Modell: '+(d.model||'-'),14,31);doc.text('AO/order: '+(d.ao||'-')+'   Nästa provning: '+(d.nextDate||'-'),14,37);doc.text('Status: '+(stat[d.status]||'-')+'   Signatur: '+(d.signature||'-'),14,43);let y=52;CHECKS.forEach(([n,t])=>{const c=d.checks[n],lines=doc.splitTextToSize(n+' '+t,115);doc.text(lines,14,y);doc.text(res[c.result]||res[''],134,y);if(c.note)doc.text(doc.splitTextToSize(c.note,45),14,y+lines.length*4);y+=Math.max(8,lines.length*4+(c.note?5:0));if(y>270){doc.addPage();y=18}});if(d.notes){doc.setFontSize(10);doc.text(doc.splitTextToSize('Allmän info: '+d.notes,180),14,Math.min(y+3,275))}});doc.save('provningsprotokoll-dorrautomatik.pdf')};